name: run python chat

on:
  workflow_dispatch:

env:
  api_key: ${{ secrets.OPENAI_API_KEY }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python chat
        run: |
              python chatuse.py
                    
