name: run python chat

on:
  workflow_dispatch:

env:
  api_key: ${{ secrets.OPENAI_API_KEY }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python chat
        run: |
          pip install requests
          python chatuse.py
